version: '3'
services:
  server:
    image: nginx
    ports:
     - "8080:80"
    volumes:
     - ./src:/src
     - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
     - web-network
  php:
    image: php:7-fpm
    volumes:
     - ./src:/src
    networks:
     - web-network
networks:
    web-network:
        driver: bridge
